name: boat_monitor32
description: A Flutter app that integrates Firebase Cloud Messaging
publish_to: 'none'
version: 2.5.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
